; se esta usando expr_modulo, expr_relacional, expr_logica de sus respectivos archivos
; se esta usando fin_sentencia de el archivo var_arrays.bnf


expr_retorno ::= expr_modulo
               | expr_relacional
               | expr_logica

return ::= "return"
break ::= "break"
if ::= "if"
elif ::= "elif"
else ::= "else"
while ::= "while"
for ::= "for"

sent_return ::= return expr_retorno fin_sentencia | return fin_sentencia

sent_break ::= break fin_sentencia

condicion ::= expr_relacional | expr_logica

bloque ::= open_llaves sentencia* close_llaves

sentencia ::= sentencia_var | sent_return | sent_break | sent_read | sent_write | sent_if | sent_while | sent_for

sent_if ::= if condicion bloque sent_elif* sent_else?
sent_elif ::= elif condicion bloque
sent_else ::= else bloque

sent_while ::= while condicion bloque
sent_for ::= for sentencia_var condicion fin_sentencia expr_unaria bloque